### ISSUE TITLE
Infinite-scroll without gridview or listview

### ISSUE THREAD

**Issue by mramdhani** [nirvana-msu/yii2-infinite-scroll#10]
can i using Infinite-scroll without gridview or listview? give me an example please.

**Comment by nirvana-msu** [comment]
This extension works just like any other pager in Yii2, such as e.g. [`LinkPager`](http://www.yiiframework.com/doc-2.0/yii-widgets-linkpager.html). In particular, it does not force you to use `GridView` or `ListView` (and knows nothing about them), but it does require a [`Pagination`](http://www.yiiframework.com/doc-2.0/yii-data-pagination.html) object.

So whatever example you can think of where you could use `LinkPager`, would also be an example where you could use `InfiniteScrollPager` instead.
