### ISSUE TITLE
Cannot load next set of items if using div container's scrollbar

### ISSUE THREAD

**Issue by m26404020** [nirvana-msu/yii2-infinite-scroll#16]
I have a listview using this extension inside a div container. It can load the next set of items if I use browser's vertical scrollbar, but not with div container's scrollbar. Does it only reacts to browser's scrollbar?

**Comment by nirvana-msu** [comment]
I have not tried using it like that. This Yii2 extension, however, is just a thin wrapper around the underlying [infinite-scroll](https://github.com/metafizzy/infinite-scroll) jQuery plugin. I highly doubt there's something specific to this extension in what you're asking. Please check if it can be done in the upstream plugin - and if so, which options you might need to pass to configure it etc. If you end up discovering that it's possible to do with the plugin itself, but not with this extension, please report it here with more details.

Cheers.
