### ISSUE TITLE
Can't install via composer

### ISSUE THREAD

**Issue by jbazant** [nirvana-msu/yii2-infinite-scroll#2]
Package cannot be installed via composer, seems like dependency bower-asset/jquery-infinite-scroll no longer exists

**Comment by nirvana-msu** [comment]
The dependency didn't go anywhere:
http://bower.io/search/?q=infinite-scroll
https://github.com/infinite-scroll/infinite-scroll/blob/master/bower.json

Installation through composer works fine. Check minimum stability requirement in your `composer.json`.
