### ISSUE TITLE
How/Can I use this with jquery masonry?

### ISSUE THREAD

**Issue by con322** [nirvana-msu/yii2-infinite-scroll#3]
I was wondering can this be integrated with jquery masonry so that when more items are loaded the masonry is reapplied.

I know jquery masonry has append but not sure how i'd integrate it so that it's triggered when the new items are loaded.

Thanks any direction is appreciated.

**Comment by nirvana-msu** [comment]
This extension merely helps you register javascript code to initialize plugin. You can register masonry behavior by configuring `behavior` to be `InfiniteScrollPager::BEHAVIOR_TWITTER` (a similar example is included in the documentation).

I have never used it with masonry, so cannot answer your question. You should raise all plugin-related questions directly in [infinite-scroll](https://github.com/infinite-scroll/infinite-scroll) repository.

**Comment by con322** [comment]
Okay thanks for pointing me in the right direction, but how do I add the custom call back if the javascript is added via the extension?

For example I have found the following link

```
$container.infinitescroll({
 navSelector  : '#paging',
nextSelector : '#paging a',
itemSelector : '.col', 
behavior: 'twitter',
loading: {
  msgText: 'Loading...',
      finishedMsg: 'Loaded all!'
    }
  },
  // call Isotope as a callback
  function( newElements ) {
    $container.isotope( 'appended', $( newElements ) ); 
  }
);
```

**Comment by nirvana-msu** [comment]
It is described in the readme - set `contentLoadedCallback` property
