### ISSUE TITLE
Reverse Infinite Scroll Feature

### ISSUE THREAD

**Issue by IvoPereira** [nirvana-msu/yii2-infinite-scroll#6]
Hello,

Do you have anything planned for such a feature?

Something like replicating the Facebook Messages system. Basically, instead of triggering the event on scrolling down, it would trigger it on scrolling up.

Thanks

**Comment by nirvana-msu** [comment]
This extension is merely a wrapper for [infinite-scroll](https://github.com/infinite-scroll/infinite-scroll) jQuery plugin. If and when such functionality is implemented in the plugin, I would be happy to update this yii2 extension. You should raise this issue with plugin developers directly in the respective repository.

For the reference, this feature has been discussed already in [this issue](https://github.com/infinite-scroll/infinite-scroll/issues/562). There's a [fork](https://github.com/outdooricon/infinite-scroll-with-history) that implements what you want (I've never tried it, though), but it hasn't been updated for several years and was never merged into the main repo.
